[package]
name = "holochain_wasm_engine"
version = "0.0.43-alpha3"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"
description = "Implements holochain_wasmer for the conductor"
keywords = ["holochain", "holo", "p2p", "network", "simulation"]
license = "GPL-3.0-only"
readme = "README.md"
documentation = "https://github.com/holochain/holochain-rust"
repository = "https://github.com/holochain/holochain-rust"

[dependencies]
holochain_wasmer_host = "=0.0.14"
